version: "3.1"
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 127.0.0.1:3307:3306

  webserver:
    image: nginx:alpine
    container_name: docker-webserver
    volumes:
      - .:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  php:
    build: docker/php-fpm
    container_name: d-php
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
